version: '3.8'

services:
  postgres-catalogo:
    image: postgres:15-alpine
    container_name: postgres-catalogo-libros
    environment:
      POSTGRES_DB: libros_db
      POSTGRES_USER: libreria
      POSTGRES_PASSWORD: catalogos_libreria
    ports:
      - "5432:5432"
    volumes:
      - datos_postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - red-catalogo

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-catalogo-libros
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-catalogo
    networks:
      - red-catalogo

volumes:
  datos_postgres:

networks:
  red-catalogo:
    driver: bridge
