server:
  port: 8081

spring:
  application:
    name: ms-books-catalogue

  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue_db
    username: catalogue_user
    password: catalogue_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.relatosdepapel.catalogue: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
